### ISSUE TITLE
Menu bug on mobile (chrome)

### ISSUE THREAD

**Issue by jcarroll2007** [sathomas/STEM#64] opened 2015-04-30 19:38 UTC
I was just messing around with the look and feel on my phone (using the chrome browser) and I came across a bug with the menu. While on the "search the incubator" view I opened the menu and selected one of the menu items to return to the main view. The url updated but the state didn't change and the whole site became unresponsive. 

To recreate the issue: 
1. on a mobile phone go to stemincubator.org
2. press the magnifying glass search icon
3. After the search page has loaded, press `menu` on the site's navigation bar
4. Select one of the menu options
5. The site should now be unresponsive

I'm not exactly sure what is happening. The site does actually begin responding again but it becomes very slow and almost impossible to use.

**Comment by jcarroll2007** [comment] 2015-04-30 19:40
Emulating this in the browser does not yield the same result

**Comment by sathomas** [comment] 2015-05-01 11:49
Some suggestions for this one.
1. Obvious first step is to tether an android device (or remote debug it) and check the dev console. If we're lucky, there will be an error message. (Doesn't seem likely though.)
2. The multiple maps with hundreds of markers is a definite performance problem. (I've tried to argue for a more efficient approach, but to no avail so far.) If the android device is relatively low powered, that could be the cause of the sluggishness. How does the site perform if you just scroll down to the maps instead of using the menu?
3. Might there me a conflict between the browser's handling of URL fragments (e.g. `#admins`) and the Backbone router? Try commenting out the explicit routes in `app.js` and see if that clears up the problem.

**Comment by gscoppino** [comment] 2015-05-01 13:39
I was able to reproduce on production using the latest `Chrome` stable for Android. I'm also getting the same problem on production using `Chrome` dev tools (latest stable) to emulate both an iPhone 5 and Nexus 5. I didn't receive any errors from the `console` and there were no pending requests on the network tab of Chrome dev tools. It does NOT occur for me in latest `Firefox`, `Firefox` in responsive design mode, `Internet Explorer 10`, or `Internet Explorer 10` with `IE9 user agent`. 

`jcarroll2007`, Were you emulating in `Firefox` when you were unable to reproduce the results? If so, this could be a `Chrome/Webkit` bug. I do not have access to `Safari` to test there, unfortunately.

For reference, Building and running the latest `sathomas/master` locally, the bug no longer occurs, in any of the browsers referenced (except `Safari` which I have not tested), in any of the configurations referenced.

-- Giuseppe

**Comment by gscoppino** [comment] 2015-05-01 13:43
`sathomas`: Number 2 is probably not the case since it happens in Chrome dev tools on a desktop with mid-range PC specs.

-- Giuseppe

**Comment by sathomas** [comment] 2015-05-01 13:44
That's weird. `master` is exactly what's running in production. (At least it should be :) Both were updated this morning.

Just for sanity, can you try three things:
1. The latest `master` built and running locally.
2. The latest production.
3. The [1.0.4 release](https://github.com/sathomas/STEM/releases/tag/1.0.4) (This will be the "built" version of `master`) locally.

In theory, all three of those should be identical. If they're not, that could be a clue.

**Comment by gscoppino** [comment] 2015-05-01 13:51
~~I can only reproduce the problem in the latest `production`. `1.0.4` and `master` do not have the issue in Chrome dev tools. I haven't tried either `1.0.4` or `master` directly on a phone.~~

My bad, this was just a configuration thing, probably because I forgot to run `grunt clean` and `grunt build`. See below comment.

**Comment by gscoppino** [comment] 2015-05-01 14:07
I went and cloned `upstream` directly rather than just pulling your `master` into mine, and with fresh builds, it is now its reproducible for me in `1.0.4` and `master` as well.

**Comment by sathomas** [comment] 2015-05-01 17:41
As best as I can tell:
- If you load the site in desktop Chrome and then switch to responsive view in the developer tools, then the bug doesn't occur.
- If you switch Chrome to responsive view _before_ loading the site, the bug occurs.

Also, once the initial "dead time" clears, I have to quit and reload Chrome to get it to happen again.

If anyone has any contrary experiences, chime in. Unfortunately, though it appears that I can reliably reproduce the bug (using the second procedure), I'm not seeing any clues as to its cause. During the "dead time", the browser is 99.43% idle, memory use is not excessive, and no network requests are occurring.

**Comment by sathomas** [comment] 2015-05-01 18:17
Think I've found the problem. For some reason, Chrome on Android isn't repainting when the section positions are swapped. The "dead time" is apparently just a random amount of time until the browser decides to repaint. I can't think of any reason that's not a bug in Chrome, but haven't had the time to research it yet. In the meantime, I'm working on a quick fix.

**Comment by sathomas** [comment] 2015-05-01 18:25
Fix is now live in production. @jcarroll2007, @gscoppino can you guys verify as well? I don't trust my own testing completely.

**Comment by gscoppino** [comment] 2015-05-04 14:37
I'm not longer able to reproduce the problem in Chrome on Android or in Chrome device mode :)

**Comment by sathomas** [comment] 2015-05-04 14:38
Sweet. Gonna close the issue then.

**Closed as completed by sathomas** 2015-05-04 14:38 UTC

**Comment by jcarroll2007** [comment] 2015-05-05 12:44
Working for me as well!
